app_addFriend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_updatestatus/urls.py
from django.conf.urls import url
from .views import index, add_status
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

tuita/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import app_profile.urls as index_app_profile
import app_updatestatus.urls as index_app_updatestatus
import app_addFriend.urls as index_friend
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/',include(index_app_profile,namespace='profile')),
    url(r'^friend/',include(index_friend,namespace='add_friend')),
    url(r'^update/',include(index_app_updatestatus,namespace='update')),
    url(r'^$',RedirectView.as_view(url='/profile/', permanent=False), name='index'),
]

app_addFriend/models.py
from django.db import models

class Friends(models.Model):
    name = models.CharField(max_length=27)
    url = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

app_profile/models.py
from django.db import models

# Create your models here.

app_stats/models.py
from django.db import models

# Create your models here.

app_updatestatus/models.py
from django.db import models

class Status(models.Model):
	isi = models.CharField(max_length=140)
	created_date = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-created_date']

app_addFriend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan nama teman'
    }
    description_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan url teman'
    }

    name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    url = forms.CharField(label='URL', required=True, widget=forms.TextInput(attrs=description_attrs))

app_updatestatus/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong dong isi :c',
    }
    isi_attrs = {
        'type': 'text',
        'cols':70,
        'rows':4,
        'class': 'status-form-textarea',
        'placeholder':'Mikirin apaan ???'
    }

    isi = forms.CharField(label='', required=True, max_length=140, widget=forms.Textarea(attrs=isi_attrs))
    

app_addFriend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Friend_Form
from .models import Friends

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Priscilla Tiffany" #TODO Implement yourname
    allFriends = Friends.objects.all()
    response['allFriends'] = allFriends
    response['add_friend_form'] = Add_Friend_Form
    return render(request, 'index_friend.html', response)

def add_friend(request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friends(name=response['name'],url=response['url'])
        friend.save()
        return HttpResponseRedirect('/friend/')
    else:
        return HttpResponseRedirect('/friend/')

app_profile/views.py
from django.shortcuts import render

# Create your views here.
nama = 'Donatello'
ulangTahun = '05 Oktober'
gender = 'Rather not say'
expertise = ['Kungfu','Fight','Eat Pizza']
desc = 'I am so smart turtle who likes to eat pizza. Feel free to visit me'
email = 'donnatelo@ninja.com'
img_url = "https://i.ebayimg.com/images/g/w58AAOSwhMpT0Rdq/s-l300.jpg"

def index(request):
	response={'name':nama,'birthDate':ulangTahun, 'gender':gender,'expertise':expertise,'description':desc,'email':email,
	'img_url' : img_url}
	return render(request,'profile.html',response)

app_stats/views.py
from django.shortcuts import render

# Create your views here.

app_updatestatus/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from app_profile.views import nama, img_url


# Create your views here.
response = {}

def index(request):
    response['author'] = "Donatello"
    status = Status.objects.all()
    response['status'] = status
    html = 'update.html'
    response['status_form'] = Status_Form
    response['nama'] = nama
    response['img_url'] = img_url
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == "POST" and form.is_valid()):
        response['isi'] = request.POST['isi']
        status = Status(isi = response['isi'])
        status.save()
        return HttpResponseRedirect('/update/')
    else:
        return HttpResponseRedirect('/update/')

app_addFriend/templates/index_friend.html
{% block content %}
<h2 class="main-title">Add Friend</h2>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'add_friend:add_friend' %}">
            {% csrf_token %}
            <table>
            {% for form in add_friend_form %}
            <tr>
               <td>
                {{ form.label_tag }}
               </td>
               <td>
                {{ form }}
               </td>
            </tr>
            {% endfor %}
            </table>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">List friend</h2>
        <div class="flex">
            {% if allFriends %}
            <table>
                {% for data in allFriends %}
                    <div class="flex-item">
                        <div class="to-do-list">
                           <tr>
                                <td>{{data.name}} </td>
                                <td><a href="{{data.url}}">{{data.url}}</a></td>
                                <td>Added {{data.created_date}}</td>
                            </tr>
                        </div>
                    </div>
                {% endfor %}
            </table>
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

app_profile/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
		<h2>Profile<h2>
    <meta charset="UTF-8">
    <title>tuita</title>
</head>
<img src={{img_url}} style="width:10rem; height:10rem;"/>
<body>
    <article> {{ name }}</article>
		<article> Birthday {{ birthDate }} </article>
		<article> Expertise  
		{% for expert in expertise %}
			 {{ expert }}
		{% endfor %} </article>
		<article> Description {{ description }} </article>
		<article> Email {{ email }} </article>

</body>
</html>

app_updatestatus/templates/update.html
<style type="text/css">
	body{
		margin-left: 80px;
		margin-right: 80px;

	}
	img {
		float: left;
		margin: 0 0 10px 10px;
	}
	div {
		clear: left;
	}
	.clearfix{
		overflow: auto;
	}
	.isi-status{
		font-family: "Helvetica";
		margin-left: 10px;
	}
	.date-added{
		color: grey;
		font-size: 76%;
		margin-left: 10px;
	}


</style>

{% block content %}


<body>

<section name="input-list" id="input-list">
	<div class="container">
		<form id="form" method="POST" action="{% url 'update:add_status' %}">
			<h2>Update Status</h2>
			{% csrf_token %}
			{{ status_form }}
			<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
			<br>
		</form>
	</div>
</section>

<section name="my-list" id="my-list">
    <div class="container">
        <div class="flex">
            {% if status %}
                {% for data in status %}
                    <div class="flex-item">
                        <div class="status-list">
							<div class="clear-fix">
                                <img src={{img_url}} style="width:3rem; height:3rem;"/>
                                <strong>{{nama}}</strong>
                            </div>
                            <div class="isi-status">
                                {{data.isi}}
                            </div>
                            <div class="date-added">
                                {{data.created_date}}
                            </div>
                        </div>
                    </div>
					</br>
                {% endfor %}
            {% else %}
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}
</body>